# 2.11.2020 

# **Analysis, Exercise 2**


**Description of analysed data**

The aim of this study was to set light on the relationship between learning approaches and students' achievements in an introductory statistics course in Finland.

The data set (N = 166) used in this report consisted of 7 variables: Gender, Age, attitude, Deep approach, Surface approach, Strategic approach and total points. The participants were 17-55-years-olds (mean = 25.5) and 66 % of them were Female.

Read more about the used scales and variables from 
[here](https://www.mv.helsinki.fi/home/kvehkala/JYTmooc/JYTOPKYS2-meta.txt)

R script for graphical overview of the data:

```{r}
analysisdata <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", sep=",", header=TRUE)

#Description of data set
library(Hmisc)
describe(analysisdata)
```

Here we go again...


*Describe the work you have done this week and summarize your learning.*

- Describe your work and results clearly. 
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods.
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using.
